### ISSUE TITLE
Load Balancer stack is failing and unable to create the custom roles.

### ISSUE THREAD

**Issue by Shaik9999** [aws-quickstart/quickstart-kubernetes-resource-provider#14]
Load Balancer stack is failing and unable to create the custom roles. 

 "functionName": "awsqs-kubernetes-resource-apply-proxy-eks-testssbpath-hyath",
role": "arn:aws:iam::97353437:role/awsqs-kubernetes-resource",

I've update the quickstart-amazon-eks\k8s\functions\packages\kubernetesResources\vpc.py where role name is updated with /usro--sbb/ but when I deploy the stack the custom role is not showing in the cloud trail and finally stack is failing with following error.

The following resource(s) failed to create: [LoadBalancerControllerServiceAccount].

Resource handler returned message: "" (RequestToken: -d7df-10f5-51ef28a89e0c, HandlerErrorCode: InternalFailure).

My Question is from which template or lambda function is it being assumed from ? Why this stack is failing while gave the custom path.

**Comment by gargana** [comment]
There appears to be a backwards compatability issue with ruamel.yaml. Locking to "0.17.4" should fix this.

**Comment by gargana** [comment]
@Shaik9999 are you consuming this stand alone or via the [Amazon EKS Quick Start](https://github.com/aws-quickstart/quickstart-amazon-eks)?

If you are consuming the Amazon EKS Quick Start the fix is now in [main](https://github.com/aws-quickstart/quickstart-amazon-eks/pull/330)

**Comment by autodidacticon** [comment]
@gargana would this have anything to do with #21 ?

Additionally, how can we verify the ruamel fixes have been deployed into the latest eks qs packages?
