### ISSUE TITLE
CloudFormation fails to create resource of type AWSQS::Kubernetes::Resource for EKS cluster with private only API access

### ISSUE THREAD

**Issue by nbbhall** [aws-quickstart/quickstart-kubernetes-resource-provider#22]
Does AWSQS::Kubernetes::Resource support VPCConfiguration like AWSQS::Kubernetes::Helm does? From [this schema](https://github.com/aws-quickstart/quickstart-kubernetes-resource-provider/blob/857bab69db604152566a547b108c137ddc2aab40/apply/awsqs-kubernetes-resource.json) it does not look like VPCConfiguration is supported. Is there an alternate way to get this working with EKS cluster which has private-only API endpoint? Thanks!

**Comment by yousufsujeel** [comment]
Any Update on this,  Does the AWSQS::Kubernetes::Resource. support Private only clusters ?

**Comment by nbbhall** [comment]
Works fine after adding following tags to public subnets:-
kubernetes.io/cluster/<cluster-name>: shared
kubernetes.io/role/elb: 1: 1

And following tags to private subnets:-
kubernetes.io/cluster/<cluster-name>: shared
kubernetes.io/role/internal-elb: 1

Also hit an issue where control plane security group had restrictive egress rules. After relaxing egress rules in control plane SG issue resolved. Tracked the security group in use by resource provider Lambda by looking at CreateNetworkInterface API call in CloudTrail
