### ISSUE TITLE
How to integrate kubernetes resource provider

### ISSUE THREAD

**Issue by amitkatyal** [aws-quickstart/quickstart-kubernetes-resource-provider#7]
Hi Team,

I would like to use AWSQS::Kubernetes:Resource custom resource for aws load balancer template same like AWSQS::Kubernetes::Helm. I could the get deployment template under helm resource provider repo to register custom resource with cloud formation registry. However, I did not get clarity on how to register AWSQS::Kubernetes:Resource.

Could you please provide some insights to it ?

**Comment by 4ndr4s** [comment]
@amitkatyal  did you find how it works, I'm facing a similar issue, trying to find the best way to update a ConfigMap

**Comment by amitkatyal** [comment]
Not sure if you get a chance to look at the was quickstart-amazon-eks. This makes uses of all the customer resources.
https://github.com/aws-quickstart/quickstart-amazon-eks
